apiVersion: v1
kind: Service
metadata:
  name: merutable-hl
  namespace: merutable
  labels:
    app.kubernetes.io/name: merutable
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: merutable
  ports:
    - name: grpc
      port: 9100
      targetPort: 9100
      protocol: TCP
